export const brandQuotes = [
  "Taken from the best. Bred for the rest.",
  "Sourced from the elite. Brought to the street.",
  "Stolen from the top. Grown for your crop.",
  "Pulled from the pros. Bred for your grows.",
  "Kept by the few. Handed down to you.",
  "Locked in the vault. Bred without a fault.",
  "Found with the stars. Bred for your jars.",
  "Lifted from the crown. Bred to hold it down.",
  "Secured from the stash. Grown for the hash.",
  "Freed from the lock. Bred for the block.",
  "Grabbed from the rich. Grown without a hitch.",
  "Hunted for the fire. Bred to take you higher.",
  "Chased by the bold. Bred to yield gold.",
  "Taken from the kings. Bred for better things.",
  "Stolen from the hoard. Grown for your reward.",
  "Snatched from the peak. Bred for the unique.",
  "Plucked from the rare. Bred with expert care.",
  "Hidden by the greed. Liberated in the seed.",
  "Pinched from the prize. Grown before your eyes.",
  "Kept on the sly. Bred for you and I.",
  "Tracked for the fame. Bred to change the game.",
  "Sourced from the prime. Heavy every time.",
  "Hunted in the dark. Bred to leave a mark.",
  "Snatched from the shelf. Grown to prove yourself.",
  "Hoarded by the greats. Bred for higher states.",
  "Chased for the frost. Grown to be the boss.",
  "Saved from the hype. Bred exactly right.",
  "Pulled from the loud. Bred for the crowd.",
  "Hunted by the crew. Handed straight to you.",
  "Lifted from the throne. Bred to be your own.",
] as const;

export type BrandQuote = (typeof brandQuotes)[number];
