export const cartCopy = {
  add: "ADD TO CART",
  added: "Added to cart.",
  already: "Already in the cart.",
  openCart: "Open cart",
  cart: "CART",
  empty: "THE CART IS EMPTY.",
  emptyHint: "Open The Vault and add a strain.",
  continue: "CONTINUE IN THE VAULT",
  checkout: "CHECKOUT",
  remove: "REMOVE",
  clear: "CLEAR CART",
  cancel: "CANCEL",
  seedQuantity: "SEEDS IN THIS OPTION",
  perSeed: "each",
  optionPrice: "Option price",
  cartOptions: "OPTIONS IN CART",
  subtotal: "Subtotal",
  merchandiseSubtotal: "Merchandise subtotal",
  orderTotal: "Order total",
  shippingAmount: "Shipping",
  shippingFree: "FREE",
  freeRandomFive: "FREE RANDOM 5 PACK",
  freeLabel: "FREE",
  promotionUnlocked: "FREE SHIPPING + FREE RANDOM 5 PACK",
  spendMoreForPromotion: "SPEND {amount} MORE FOR FREE SHIPPING + A FREE RANDOM 5 PACK",
  lineTotal: "Line total",
  unavailable: "This file is not available to add.",
  comingSoon: "This release is still coming into range.",
  soldOut: "This file is sold out.",
  inquiryOnly: "This file is inquiry only.",
  fileStatus: "FILE STATUS",
  bulkTitle: "LOOKING FOR A CUSTOM QUANTITY?",
  bulkBody:
    "Standard storefront options are 1, 2, 3, or 5 seeds. Tell Bandit Genetics what you need for a custom bulk run. Custom bulk stays on the Contact line, not in the seed option selector.",
  bulkCta: "REQUEST A CUSTOM BULK ORDER",
  toastView: "VIEW CART",
  paymentOff:
    "Card checkout cannot start because Stripe is not configured on this server. Nothing will be charged by card. PAY LATER / PAY WITH CRYPTO remains available. Submitting crypto does not mark the order paid.",
  checkoutTitle: "CHECKOUT",
  checkoutKicker: "THE DESK",
  checkoutIntro:
    "Review the strains on this ticket. Card checkout cannot start until Stripe is configured on this server. PAY LATER / PAY WITH CRYPTO is available. Submitting crypto does not mark the order paid.",
  checkoutIntroLive:
    "Review the strains on this ticket. Choose one payment method. Card details stay on Stripe Checkout. Crypto is not marked paid until Bandit Genetics verifies it.",
  continueStripe: "CHECKOUT WITH CARD",
  checkoutWithCard: "CHECKOUT WITH CARD",
  payLaterCrypto: "PAY LATER / PAY WITH CRYPTO",
  paymentMethod: "PAYMENT METHOD",
  payWithCard: "CREDIT / DEBIT CARD",
  payWithCrypto: "CRYPTO",
  choosePayment: "Choose one payment method.",
  cardCheckoutNote:
    "Card details are entered on Stripe Checkout. This site never handles raw card numbers. Stripe chooses which payment methods to show for the connected account.",
  cryptoNote:
    "This is not financing and not credit. You submit the order unpaid, then send cryptocurrency to the Bandit Genetics receiving address shown for the network you select.",
  cryptoVerifyNote:
    "CRYPTO PAYMENT VERIFICATION IS MANUAL. A transaction hash is optional customer information only. It does not mark the order paid.",
  cryptoAmountNote:
    "The amount due is the USD order total from this ticket. This site does not convert USD into BTC, ETH, or SOL. Confirm the crypto amount through Bandit Genetics payment instructions before sending.",
  invalidCrypto: "Choose Bitcoin, Ethereum, or Solana.",
  cryptoSubmitted: "ORDER SUBMITTED",
  cryptoPaymentRequired: "PAYMENT REQUIRED",
  cryptoUnpaid:
    "Payment has not been verified. This order is unpaid.",
  cryptoVerified:
    "Bandit Genetics marked this order paid after manual verification.",
  cryptoHashLabel: "Transaction hash (optional)",
  cryptoCopy: "COPY ADDRESS",
  cryptoCopied: "COPIED",
  stripeAddressNote:
    "For card checkout, delivery address is collected on Stripe Checkout. Shipping is calculated on this server from the paid merchandise subtotal.",
  cancelledCheckout:
    "Checkout was not completed. Nothing was charged. Your cart is still here.",
  invalidItems:
    "One or more items in the cart could not be checked out. Remove unavailable strains and try again.",
  successTitle: "CHECKOUT RETURN",
  successKicker: "THE DESK",
  successPending:
    "You returned from Stripe. Payment is still being confirmed. This page does not mark an order as paid by itself.",
  successPaid:
    "Stripe confirmed the payment and the internal order is marked paid.",
  successMissing:
    "This checkout return could not be matched to a Stripe session. No payment is assumed.",
  successFailed:
    "Payment did not complete. You can return to checkout and try again. Nothing is marked paid.",
  placeOrder: "PLACE ORDER",
  placeOrderDisabled: "PAYMENT NOT ENABLED",
  name: "Name",
  email: "Email",
  line1: "Street address",
  city: "City",
  region: "State / region",
  postal: "Postal code",
  country: "Country",
  required: "This field is required.",
  invalidEmail: "Enter a valid email address.",
  emptyCart: "Add a strain before checkout.",
  summary: "ORDER SUMMARY",
  shipping: "SHIPPING",
  payment: "PAYMENT METHOD",
  taxNote: "Tax is not calculated on this site.",
  network: "The checkout could not continue. Check the connection and try again.",
  chooseSeeds:
    "Choose how many seeds this option includes. This is not how many cart items you want.",
} as const;
