export const cartCopy = {
  add: "ADD TO CART",
  added: "Added to cart.",
  already: "Already in the cart.",
  openCart: "Open cart",
  cart: "CART",
  empty: "THE CART IS EMPTY.",
  emptyHint: "Open The Vault and add a strain.",
  continue: "CONTINUE IN THE VAULT",
  backToTheVault: "BACK TO THE VAULT",
  checkout: "CHECKOUT",
  remove: "REMOVE",
  clear: "CLEAR CART",
  cancel: "CANCEL",
  seedQuantity: "SEEDS IN THIS OPTION",
  perSeed: "each",
  optionPrice: "Option price",
  cartOptions: "OPTIONS IN CART",
  subtotal: "Subtotal",
  merchandiseSubtotal: "Merchandise subtotal",
  orderTotal: "Order total",
  shippingAmount: "Shipping",
  shippingFree: "FREE",
  promotionalGift: "PROMOTIONAL GIFT",
  freeFivePack: "FREE 5 SEED PACK",
  freeLabel: "FREE",
  chooseFreeFive: "CHOOSE YOUR FREE 5 SEED PACK",
  chooseFreeFiveHint: "Pick any eligible strain from The Vault.",
  changeFreeGift: "CHANGE FREE GIFT",
  giftRequired: "Choose your free 5 seed pack to continue.",
  invalidGift: "That promotional strain is not available. Choose another from The Vault.",
  promotionChooseGift: "FREE SHIPPING + CHOOSE YOUR FREE 5 SEED PACK",
  promotionUnlocked: "FREE SHIPPING + FREE 5 SEED PACK SELECTED",
  spendMoreForPromotion: "SPEND {amount} MORE FOR FREE SHIPPING + A FREE 5 SEED PACK",
  lineTotal: "Line total",
  unavailable: "This file is not available to add.",
  comingSoon: "This release is still coming into range.",
  soldOut: "This file is sold out.",
  inquiryOnly: "This file is inquiry only.",
  fileStatus: "FILE STATUS",
  bulkTitle: "LOOKING FOR A CUSTOM QUANTITY?",
  bulkBody:
    "Standard storefront options are 1, 2, 3, or 5 seeds. Tell Bandit Genetics what you need for a custom bulk run. Custom bulk stays on the Contact line, not in the seed option selector.",
  bulkCta: "REQUEST A CUSTOM BULK ORDER",
  toastView: "VIEW CART",
  emailOrderCta: "EMAIL US TO PLACE AN ORDER",
  emailOrderBody: "You can contact us at",
  emailOrderCryptoNote:
    "Cryptocurrency checkout remains available if you prefer to pay that way.",
  emailOrderCompact: "Email us to place an order:",
  checkoutTitle: "CHECKOUT",
  checkoutKicker: "THE DESK",
  checkoutIntro:
    "Review the strains on this ticket. Email support@banditgenetics.com to place an order, or use cryptocurrency checkout. Crypto is not marked paid until Bandit Genetics verifies it.",
  payLaterCrypto: "PAY LATER / PAY WITH CRYPTO",
  paymentMethod: "HOW TO ORDER",
  payWithCrypto: "CRYPTO",
  choosePayment:
    "Email us to place an order, or complete cryptocurrency checkout below.",
  cryptoNote:
    "This is not financing and not credit. You submit the order unpaid, then send cryptocurrency to the Bandit Genetics receiving address shown for the network you select.",
  cryptoVerifyNote:
    "CRYPTO PAYMENT VERIFICATION IS MANUAL. A transaction hash is optional customer information only. It does not mark the order paid.",
  cryptoAmountNote:
    "The amount due is the USD order total from this ticket. This site does not convert USD into BTC, ETH, or SOL. Confirm the crypto amount through Bandit Genetics payment instructions before sending.",
  invalidCrypto: "Choose Bitcoin, Ethereum, or Solana.",
  cryptoSubmitted: "ORDER SUBMITTED",
  cryptoPaymentRequired: "PAYMENT REQUIRED",
  cryptoUnpaid:
    "Payment has not been verified. This order is unpaid.",
  cryptoVerified:
    "Bandit Genetics marked this order paid after manual verification.",
  cryptoHashLabel: "Transaction hash (optional)",
  cryptoCopy: "COPY ADDRESS",
  cryptoCopied: "COPIED",
  cancelledCheckout:
    "Checkout was not completed. Your cart is still here.",
  invalidItems:
    "One or more items in the cart could not be checked out. Remove unavailable strains and try again.",
  orderLabel: "Order",
  cryptoMissing: "This crypto checkout ticket could not be found.",
  placeOrder: "PLACE ORDER",
  name: "Name",
  email: "Email",
  line1: "Street address",
  city: "City",
  region: "State / region",
  postal: "Postal code",
  country: "Country",
  required: "This field is required.",
  invalidEmail: "Enter a valid email address.",
  emptyCart: "Add a strain before checkout.",
  summary: "ORDER SUMMARY",
  shipping: "SHIPPING",
  payment: "PAYMENT METHOD",
  taxNote: "Tax is not calculated on this site.",
  network: "The checkout could not continue. Check the connection and try again.",
  chooseSeeds:
    "Choose how many seeds this option includes. This is not how many cart items you want.",
} as const;
