export const cartCopy = {
  add: "ADD TO CART",
  added: "Added to cart.",
  already: "Already in the cart.",
  openCart: "Open cart",
  cart: "CART",
  empty: "THE CART IS EMPTY.",
  emptyHint: "Open The Vault and add a strain.",
  continue: "CONTINUE IN THE VAULT",
  checkout: "CHECKOUT",
  remove: "REMOVE",
  clear: "CLEAR CART",
  cancel: "CANCEL",
  seedQuantity: "SEED QUANTITY",
  perSeed: "PER SEED",
  subtotal: "Subtotal",
  orderTotal: "Order total",
  lineTotal: "Line total",
  unavailable: "This file is not available to add.",
  comingSoon: "This release is still coming into range.",
  soldOut: "This file is sold out.",
  inquiryOnly: "This file is inquiry only.",
  fileStatus: "FILE STATUS",
  bulkTitle: "LOOKING FOR A CUSTOM QUANTITY?",
  bulkBody:
    "Standard storefront quantities are 1, 2, 3, or 5 seeds. Tell Bandit Genetics what you need for a custom bulk run. Custom bulk stays on the Contact line, not in the seed quantity selector.",
  bulkCta: "REQUEST A CUSTOM BULK ORDER",
  toastView: "VIEW CART",
  paymentOff:
    "Payment processing is not currently enabled. Nothing will be charged.",
  checkoutTitle: "CHECKOUT",
  checkoutKicker: "THE DESK",
  checkoutIntro:
    "Review the strains on this ticket. Payment is not connected yet. This page will not take a card or complete a purchase.",
  placeOrder: "PLACE ORDER",
  placeOrderDisabled: "PAYMENT NOT ENABLED",
  name: "Name",
  email: "Email",
  line1: "Street address",
  city: "City",
  region: "State / region",
  postal: "Postal code",
  country: "Country",
  required: "This field is required.",
  invalidEmail: "Enter a valid email address.",
  emptyCart: "Add a strain before checkout.",
  summary: "ORDER SUMMARY",
  shipping: "SHIPPING",
  payment: "PAYMENT",
  taxNote: "Tax and shipping are calculated when a payment provider is connected.",
  network: "The checkout could not continue. Check the connection and try again.",
  chooseSeeds: "Choose how many individual seeds to add.",
} as const;
