export const dossierCopy = {
  classified: "CLASSIFIED GENETIC FILE",
  restricted: "RESTRICTED READ",
  lineagePanel: "THE LINEAGE",
  parentOne: "PARENT ONE",
  parentTwo: "PARENT TWO",
  combined: "COMBINED DIRECTION",
  publicLineage: "LINEAGE ON FILE",
  banditDidNotBreed: "Bandit Genetics did not create this parent.",
  banditFile: "THE BANDIT FILE",
  plant: "PLANT CHARACTER",
  flower: "FLOWER CHARACTER",
  resin: "RESIN EXPRESSION",
  color: "COLOR POTENTIAL",
  aroma: "AROMA AND FLAVOR DIRECTION",
  lineageCharacter: "LINEAGE CHARACTER",
  breeding: "BREEDING INTEREST",
  research: "RESEARCH STATUS",
  phenotype: "PHENOTYPE NOTES",
  grow: "GROW NOTES",
  quote: "DOSSIER QUOTE",
  related: "RELATED GENETICS",
  returnVault: "RETURN TO THE VAULT",
  comingSoon: "INFORMATION COMING SOON",
  phenotypePending: "PHENOTYPE DATA PENDING",
  growPending: "GROW DATA PENDING",
  quotePending: "NO FILE REMARK ON RECORD.",
  relatedEmpty: "NO SHARED PARENT OR INFLUENCE ON FILE WITH ANOTHER BANDIT CULTIVAR.",
  pendingKicker: "AWAITING BANDIT DATA",
  pendingBody:
    "This space is reserved for future Bandit Genetics observations. Nothing here is invented.",
  futureObs:
    "Future Bandit Genetics phenotype observations will land here after a real run. They are not on this file yet.",
  documented: "DOCUMENTED",
  inferred: "INFERRED",
  unknown: "UNKNOWN",
  inferredReading: "Genetic expectation from parent records. Not a Bandit garden log.",
  artworkPending: "Artwork pending",
  gallery: "FILE IMAGES",
  notFoundKicker: "FILE MISSING",
  notFoundTitle: "NO MATCH IN THE VAULT",
  notFoundBody:
    "That slug is not in the launch catalog. Return to the archive and open a real file.",
} as const;
